# -*- coding: utf-8 -*-
"""Copy of Deber UNIR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Ap8p3mjZf7JMidNnCekcb3IMNfwavME

"""
# Carga de librerías
import functools
import json
from selenium import webdriver
from selenium.webdriver.common.keys import Keys # Emular acciones de teclado
from selenium.webdriver.common.by import By # para hacer búsquedas parametrizadas
from selenium.webdriver.support.ui import WebDriverWait # para esperar a que la página cargue
from selenium.webdriver.support import expected_conditions as EC # Para condicionar WebDriverWait


"""## Paso 2 - Redireccionando a la sección de foros"""

driver.get("https://campusvirtual.unir.net/portal/site/PER1518-2-7403-222/tool/62ed58f7-740f-4395-83e2-d2eeb5ac2651/discussionForum/forumsOnly/dfForums")

"""## Paso 3 - Acceder recursivamente a los foros"""

def access_subforum(parent, first=False):
  f = {} # esto almacenara el contenido del subforo
  parent.click() # haciendo click en el foro para acceder a subforos  

  # Limite de la recursion
  limit = driver.find_elements_by_css_selector(".itemToolBar .button")
  if len(limit) > 0: 
    replies = driver.find_elements_by_css_selector("div.hierItemBlock")
    
    for reply in replies:
      key = reply.find_elements_by_css_selector("div.messageMetadata span.textPanelFooter")
      key = tuple(map(lambda x:x.text, key))
      key = functools.reduce(lambda x, y: x + " " + y, key)
      f[key] = reply.find_elements_by_css_selector("div.textPanel")[0].text

    return f

  # Este es el boton de retroceder
  backClassTag = "table.specialLink div.specialLink a"

  # Estos son los temas del foro o los subforos
  if first: tag = ".specialLink a.title"
  else: tag = ".firstChild a.messagetitlelink"

  # Obteniendo los componentes de cada foro o subforo
  search_results = driver.find_elements_by_css_selector(tag)

  # Yendo en produndidad a cada entrada de este subforo de forma recursiva
  for i in range(len(search_results)):
    sub_key = search_results[i].text # nombre del foro/subforo
    f[sub_key] = access_subforum(search_results[i]) # llamada recursiva

    # Retrocediendo para seguir con el siguiente subforo
    backClass = driver.find_elements_by_css_selector(backClassTag)[-1]
    backClass.click()

    # Esta linea es importante para volver a recuperar los elementos del DOM
    # puesto que en las llamadas recursivas este cambia
    search_results = driver.find_elements_by_css_selector(tag) 

  return f

forum = {} # foro principal

search_results = driver.find_elements_by_css_selector("table.forumHeader a.title")

for i in range(len(search_results)):
  key = search_results[i].text # nombre del foro
  forum[key] = access_subforum(search_results[i], first=True)

  # componente de retroceder
  backClass = driver.find_elements_by_css_selector("h3.specialLink a")
  if backClass is None or len(backClass) == 0: break
  
  backClass[-1].click() # El elemento de retroceder siempre es el ultimo, por eso el -1
  search_results = driver.find_elements_by_css_selector("table.forumHeader a.title")

"""## Paso 4 - Mostrar la salida"""

response_json = json.dumps(forum)
response_json = json.loads(response_json)

response_json

for key in forum.keys():
  print(key)
  # for key2 in forum[key].keys():
  #   print(key2.text)